
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Save, Send } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';

interface FormData {
  nama_pegawai: string;
  nip: string;
  unit_asal: string;
  unit_tujuan: string;
  jenis_mutasi: string;
  alasan_mutasi: string;
}

const initialFormData: FormData = {
  nama_pegawai: '',
  nip: '',
  unit_asal: '',
  unit_tujuan: '',
  jenis_mutasi: '',
  alasan_mutasi: ''
};

const jenisMutasiOptions = [
  { value: 'promosi', label: 'Promosi' },
  { value: 'rotasi', label: 'Rotasi' },
  { value: 'demosi', label: 'Demosi' },
  { value: 'pindah_unit', label: 'Pindah Unit' }
];

const unitKerjaOptions = [
  'BKPSDM',
  'Dinas Pendidikan',
  'Dinas Kesehatan',
  'Dinas Perhubungan',
  'Dinas Sosial',
  'Dinas Pertanian',
  'Dinas Perindustrian',
  'Bagian Umum',
  'Bagian Keuangan',
  'Bagian Hukum'
];

export default function BuatUsulanMutasi() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [formData, setFormData] = useState<FormData>(initialFormData);
  const [loading, setLoading] = useState(false);

  const handleInputChange = (field: keyof FormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const validateForm = (): boolean => {
    const requiredFields: (keyof FormData)[] = [
      'nama_pegawai', 
      'nip', 
      'unit_asal', 
      'unit_tujuan', 
      'jenis_mutasi', 
      'alasan_mutasi'
    ];

    for (const field of requiredFields) {
      if (!formData[field].trim()) {
        toast.error(`${field.replace('_', ' ')} wajib diisi`);
        return false;
      }
    }

    if (formData.unit_asal === formData.unit_tujuan) {
      toast.error('Unit asal dan unit tujuan tidak boleh sama');
      return false;
    }

    return true;
  };

  const handleSave = async (status: 'draft' | 'diajukan') => {
    if (!user) {
      toast.error('User tidak ditemukan');
      return;
    }

    if (!validateForm()) return;

    setLoading(true);
    try {
      const { error } = await supabase
        .from('usulan_mutasi')
        .insert({
          ...formData,
          user_id: user.id,
          status,
          nomor_usulan: '' // Will be auto-generated by trigger
        });

      if (error) throw error;

      toast.success(
        status === 'draft' 
          ? 'Usulan berhasil disimpan sebagai draft' 
          : 'Usulan berhasil diajukan'
      );
      navigate('/usulan-mutasi');
    } catch (error) {
      console.error('Error saving usulan:', error);
      toast.error('Gagal menyimpan usulan');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 space-y-6 animate-fade-in">
      {/* Header */}
      <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
        <div className="flex items-center gap-4">
          <Button 
            variant="outline" 
            size="sm"
            onClick={() => navigate('/usulan-mutasi')}
          >
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              Buat Usulan Mutasi Baru
            </h1>
            <p className="text-gray-600 mt-1">
              Lengkapi form di bawah untuk mengajukan usulan mutasi
            </p>
          </div>
        </div>
      </div>

      {/* Form */}
      <Card>
        <CardHeader>
          <CardTitle>Data Usulan Mutasi</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Nama Pegawai */}
            <div className="space-y-2">
              <Label htmlFor="nama_pegawai">Nama Pegawai *</Label>
              <Input
                id="nama_pegawai"
                value={formData.nama_pegawai}
                onChange={(e) => handleInputChange('nama_pegawai', e.target.value)}
                placeholder="Masukkan nama lengkap pegawai"
              />
            </div>

            {/* NIP */}
            <div className="space-y-2">
              <Label htmlFor="nip">NIP *</Label>
              <Input
                id="nip"
                value={formData.nip}
                onChange={(e) => handleInputChange('nip', e.target.value)}
                placeholder="Masukkan NIP pegawai"
              />
            </div>

            {/* Unit Asal */}
            <div className="space-y-2">
              <Label htmlFor="unit_asal">Unit Kerja Asal *</Label>
              <Select
                value={formData.unit_asal}
                onValueChange={(value) => handleInputChange('unit_asal', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Pilih unit kerja asal" />
                </SelectTrigger>
                <SelectContent>
                  {unitKerjaOptions.map((unit) => (
                    <SelectItem key={unit} value={unit}>
                      {unit}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Unit Tujuan */}
            <div className="space-y-2">
              <Label htmlFor="unit_tujuan">Unit Kerja Tujuan *</Label>
              <Select
                value={formData.unit_tujuan}
                onValueChange={(value) => handleInputChange('unit_tujuan', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Pilih unit kerja tujuan" />
                </SelectTrigger>
                <SelectContent>
                  {unitKerjaOptions.map((unit) => (
                    <SelectItem key={unit} value={unit}>
                      {unit}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Jenis Mutasi */}
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="jenis_mutasi">Jenis Mutasi *</Label>
              <Select
                value={formData.jenis_mutasi}
                onValueChange={(value) => handleInputChange('jenis_mutasi', value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Pilih jenis mutasi" />
                </SelectTrigger>
                <SelectContent>
                  {jenisMutasiOptions.map((jenis) => (
                    <SelectItem key={jenis.value} value={jenis.value}>
                      {jenis.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Alasan Mutasi */}
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="alasan_mutasi">Alasan Mutasi *</Label>
              <Textarea
                id="alasan_mutasi"
                value={formData.alasan_mutasi}
                onChange={(e) => handleInputChange('alasan_mutasi', e.target.value)}
                placeholder="Jelaskan alasan pengajuan mutasi"
                rows={4}
              />
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4 pt-6 border-t">
            <Button
              variant="outline"
              onClick={() => handleSave('draft')}
              disabled={loading}
            >
              <Save className="w-4 h-4 mr-2" />
              Simpan Draft
            </Button>
            <Button
              onClick={() => handleSave('diajukan')}
              disabled={loading}
              className="btn-primary"
            >
              <Send className="w-4 h-4 mr-2" />
              Ajukan Sekarang
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
